### PR TITLE
Update header.html

### PR DESCRIPTION
**Pull request by qmuhlert**
This is an update to include Google Tag Manager tracking to the blog.  Pls ask Quentin (qmuhlert@gmail.com) for any details.

### CODE REVIEW

**Comment by romansmirnov** [comment]
Hi @qmuhlert,

What is the purpose of having the Google Tag Manager? Could you please provide some details?

Thanks.

Best,
Roman

**Comment by qmuhlert** [comment]
Hi Roman,

Google Tag Manager (already deployed across Camunda.com / most of .org) is
a tag deployment platform.  It provides a lot of flexibility for the
deployment and configuration of tracking tags.  In theory, once Google Tag
Manager has been deployed, developers never need to spend time implementing
and configuring analytics tags.  This can be handled by the marketing team.


I'll be in the office tomorrow if you'd like more details - but the blog is
one of the only places we haven't deployed it yet.


Best,
-Quentin

**Comment by romansmirnov** [comment]
Quentin,

Thanks for the details.

I merged the pull request.

Best,
Roman

**Comment by qmuhlert** [comment]
Great,

Thanks!

-Quentin

**Comment by sdorokhova** [comment]
Hi @qmuhlert ,
I accidentally notices that the changes from this PR were not applied. This is the reason:

> When your work on the source files is done, you should:

> stop the grunt task
> run npm run build
> commit all the changes
> push

(copied from README)

Could you provide another PR for this?

**Pull request merged**
