### PR TITLE
Blog post for viadee Process Application Validator

### PR DESCRIPTION
**Pull request by sdibernardo**
Blog post to highlight a new major feature (data-flow validation) across process model and source code

### CODE REVIEW

**Comment by sdibernardo** [comment]
What's the status on this? :)

**Comment by ThorbenLindhauer** [comment]
Hi @sdibernardo,

sorry for the late response. The blog post looks fine. Looking at the diff, it looks like your contribution also adds a second copy of a blogpost already published in 2017. Can you please clarify the intention behind this?

Cheers,
Thorben

**Comment by sdibernardo** [comment]
There is no intention behind this. This was a mistake . I removed the duplicated file.
Thanks for pointing out!

**Comment by ThorbenLindhauer** [comment]
Thank you. I will merge your PR towards the end of next week, as we have published a bunch of posts yesterday and today already, so we can space them out a bit. I hope that's ok for you.

Cheers,
Thorben

**Comment by sdibernardo** [comment]
Yeah sure, thats perfectly fine. Thank you!

Cheers,
Sascha

**Comment by ThorbenLindhauer** [comment]
Thanks for the contribution. Your post is now published at https://blog.camunda.com/post/2019/07/viadeeprocessapplicationvalidator300/.

**Pull request closed without merging**
