### PR TITLE
feat(blog): added post for viadee process application validator

### PR DESCRIPTION
**Pull request by sdibernardo**
Thank you for publishing the post about our new tool that is able to check a BPMN process model and its underlying implementation for congruency.

### CODE REVIEW

**Comment by berndruecker** [comment]
Thanks a lot for the PR! I asked Benedikt via mail for slight changes

**Comment by berndruecker** [comment]
Awesome - thanks @sebastiansirch

**Comment by berndruecker** [comment]
@sdorokhova you can merge it - right? That would be awesome 👍

**Comment by sdorokhova** [comment]
Hi everybody,
thank you for this pull request! I merged it within ced4572. I put the spaces in the header, hope, you're OK with it.

**Comment by sebastiansirch** [comment]
Perfect, thanks!

**Pull request closed without merging**
