### PR TITLE
Blog entry on batch processing with Camunda

### PR DESCRIPTION
**Pull request by LuisePufahl**
Blog entry added to October + 3 figures

I am Phd at the BPT research group of Prof. Weske at HPI. Robert Gimbel offered me to write a blog entry on my research topic. I could not tested it locally, but I have oriented myself on existing entries and hope that I done it correctly.

Thanks for your feedback,
Luise Pufahl

### CODE REVIEW

**Comment by meyerdan** [comment]
Hi Luise,

thank you a lot for this blogpost. We will look into it next week.

Best Regards,
Daniel

**Comment by sielakos** [comment]
Hi Luise,

thank you for your contribution. I have just merged your commit. 

Best regards,
Mariusz

**Comment by LuisePufahl** [comment]
Hello,

thanks for merging it. Sorry I did a little error in the first paragraph. The link is not targeting my email. I forgot "mailto". Could you adapt this?

Thanks a lot,
Luise

**Comment by sielakos** [comment]
Hi,

No problem. I will do that today.

Best,
Mariusz

**Pull request closed without merging**
