### PR TITLE
new blog post: announcing camunda-bpm-reactor

### PR DESCRIPTION
**Pull request by jangalinski**
Hi,

Daniel ask me to provide a little introduction to "my" new community extension. Please check-read and provide feedback. Thanks for letting me use your channel to promote my idea, I am looking forward to feedback.

cu
Jan

### CODE REVIEW

**Comment by meyerdan** [comment]
Did you forget to push something?

**Comment by jangalinski** [comment]
ah .. yes

**Comment by jangalinski** [comment]
BTW: not sure if we really need the last paragraph about who  I am ... I added it to clarify that when I use "we" in the text, I am not speaking for camunda.

**Comment by meyerdan** [comment]
Great.

I did some minor edits and fixed some typos: https://github.com/camunda/blog.camunda.org/commit/8908068de91d1430da5de73a5ddbc8725a1694a1

Should I publish it?

**Comment by jangalinski** [comment]
Yes, please, looking forward to it ... and thanks for the improvements!

**Comment by meyerdan** [comment]
Great, then I'll merge and publish it

**Pull request closed without merging**
